### ISSUE TITLE
[Markdown] .gitmodules manquant ?

### ISSUE THREAD

**Issue by mmuman** [GLMF/outils_auteurs#6]
Il semble que le .gitmodule est manquant dans le dépôt.

**Comment by tcolombo** [comment]
C'est normal, je n'ai pas choisi cette structuration. C'est indiqué dans le README.

**Comment by mmuman** [comment]
J'ai du rater un truc, l'URL dans le script donne un 404…

**Comment by tcolombo** [comment]
Quelle url ?
La variable URL ? Ça je n'ai pas testé... c'était déjà installé chez moi :-)

**Comment by mmuman** [comment]
Ah ben oui alors forcément… :smile:

**Comment by tcolombo** [comment]
Du coup c'est quel fichier ? Je pensais savoir et visiblement j'ai retiré la variable URL à laquelle je pensais...

**Comment by mmuman** [comment]
Dans `Markdown/install_glmf` ?
Sinon avec le tgz décompressé au bon endroit ça devrait le faire je suppose.

**Comment by tcolombo** [comment]
J'ai corrigé l'url du README.md

**Comment by tcolombo** [comment]
Correction aussi de l'install_glmf... qui n'était pas à jour...

**Comment by tcolombo** [comment]
Et rebasage dans la foulée... merci, je pense qu'on doit avoir une version utilisable ;-)

**Comment by mmuman** [comment]
Hmm, pour info l'autosquash ne marche que si le commit a un log spécifique avec fixup! et le nom de l'autre, sinon il ne le détecte pas. Bon spas grave grave le .git à 37Mo…
