### ISSUE TITLE
Problème d'accès à `pandoc-md-auteur`

### ISSUE THREAD

**Issue by pcotret** [GLMF/outils_auteurs#8]
Il semblerait que le dépôt [pandoc-md-auteur](https://bitbucket.org/zardoz/pandoc-md-auteur) soit privé (ou, pire, supprimé). Du coup, petit problème lorsqu'on veut aller faire un `glmf new mon_article` car `pandoc-md-auteur` est un dossier vide.

**Comment by tcolombo** [comment]
Repassage en fixe de pandoc-md-auteur.
Le répertoire est privé, c'est corrigé.
